### ISSUE TITLE
Wrong @types/mime package gets installed with latest version of 'mime' package

### ISSUE THREAD

**Issue by vijay-singh-16** [broofa/mime#264]
Hi! First of all thank you for this really nice package.
Just want put a small issue to your knowledge.

The default installation of this package puts old type definitions (version 1.3.2) in 'node_modules\@types\mime' folder which makes typescript unhappy. Though this gets fixed by installation of latest version of '@types/mime' package.
But overall this is not a good experience. I don't think this is done knowingly but is left by mistake.

Please, if possible, correct the type package which gets installed when the latest version of this package is installed.

**Comment by broofa** [comment]
I don't maintain the @mime/types module. 'Not really sure what to do about this issue.  Let me know if there's anything I can do to help.  (I would be open to a PR that adds the appropriate `*.d.ts` file here, however, to help avoid the hassle of having to install `@mime/types` separately.)

**Comment by vijay-singh-16** [comment]
I have found the reason for this problem.
I am using '@vue/cli-service' package which has the following dependency path up to '@types/mime':

@vue/cli-service >> @types/webpack-dev-server >> @types/serve-static >> @types/mime

In "@types/serve-static" package the dependencies are specified as follows:

"dependencies": {
		"@types/mime": "^1",
		"@types/node": "*"
}

So, if by any means your app has direct or indirect dependency on "@types/serve-static" package, the old version of '@types/mime', with version 1.3.2, will get installed.

Also note that the '@types/mime' package doesn't get installed by installing 'mime' package, which I thought was getting auto installed with 'mime' package, I am sorry for that.

So the problem occurs when the new 'mime' package gets installed and the types come from the old '@types/mime' package. But when new '@types/mime' package is installed it replaces the old '@types/mime' package and the problem gets resolved.

Hope this post will save some time for our busy devs facing this issue.

@broofa I don't know exactly how this can be fixed. May be the maintainers of '@types/serve-static' package can upgrade the dependency on '@types/mime' to fix this.

**Comment by DukSon1224** [comment]
@vijay-singh-16 Thank you for your kindness. it's very helpful to me.

**Comment by broofa** [comment]
Keeping this closed as this is [still] not an issue with this project specifically, but I've opened [a discussion for getting @types/mime deprecated](https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/69200).

Once `@types/mime` is deprecated this issue should resolve itself (I hope)... depending on how modules have declared their @types/mime dependency.   E.g. In the latest [`@types/webpack-dev-server` dependency graph](https://npmgraph.js.org/?q=%40types%2Fwebpack-dev-server#select=exact%3A%40types%2Fmime%403.0.4), `@types/serve-static` declares `"@types/mime": "*"`, so that should pick up the latest version.

If a module has pinned their dependency to a specific version [range] of `@types/mime`, you'll need to override that by adding an entry to package.json#overrides` (for `npm` or `pnpm`) or `package.json#resolutions` (for `yarn`)

**Comment by broofa** [comment]
`@types/mime` is now deprecated (See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/69213)
