### ISSUE TITLE
Skypack broken

### ISSUE THREAD

**Issue by UlyssesZh** [broofa/mime#298]
https://cdn.skypack.dev/mime/lite

```
[Package Error] "mime@v4.0.1" could not be built. 
[1/5] Verifying package is valid…
[2/5] Installing dependencies from npm…
No matching version found for mime@4.0.1.
```

**Comment by broofa** [comment]
Can you try using the following instead and let me know if these work for you?
https://esm.sh/mime@4.0.1
https://esm.sh/mime@4.0.1/lite

**Comment by UlyssesZh** [comment]
Seems fine, but I still think the Skypack problem needs fixing because the instructions in the past use Skypack. If you decide to stop supporting Skypack, please include your decision in README.

**Comment by broofa** [comment]
Since esm.sh seems to be working I'm not particularly interested in investigating what's going on with skypack.  If you want to track that down and report back here I might consider a PR, but no promises.

As for the README, I've opted to remove 3rd-party CDN recommendations for exactly this reason... they tend not to hold up well over time.
