### ISSUE TITLE
Error with implementation in NestJS project: Error [ERR_REQUIRE_ESM]: require() of ES Module (...) not supported

### ISSUE THREAD

**Issue by uszakow** [broofa/mime#313]
### Sanity Checks

- [X] This is NOT about a specific MIME type⬌extension mapping.  Such concerns should be addressed in [the `mime-db` project](https://github.com/jshttp/mime-db/issues).  (Be sure to search the issues first.  Odds are good your concern has already been reported.)
- [X] Your issue title is descriptive and specific to the problem (i.e. search-engine friendly)
- [X] You understand what an "MRE" is, and why providing one is important.  (If not, [read this](https://stackoverflow.com/help/minimal-reproducible-example))

### MRE (link)

https://github.com/uszakow/nest-test-project.git

### MRE (supporting details)

I want to use mime lib in a new NestJS project. I add the code in `app.service.ts` file:
```
import mime from 'mime'

(...)
const mimeType = mime.getType('txt')
console.log('mimeType', mimeType)
```

Actual behavior:  an error
```
const mime_1 = require("mime");

Error [ERR_REQUIRE_ESM]: require() of ES Module /file_name/ not supported.
```

Expected behavior: project can be built

**Comment by JLoveI** [comment]
Same issue

**Comment by broofa** [comment]
Works for me ...

```bash
$ git clone https://github.com/uszakow/nest-test-project.git

[...]

$ cd nest-test-project.git

[...]

$ npm install

[...]

$ npm run build

> nest-test-project@0.0.1 build
> nest build

[... build runs with no errors]
```

> `Error [ERR_REQUIRE_ESM]: require() of ES Module /file_name/ not supported.`

I suspect `nest` is compiling your TS to CommonJS (using `require()` instead of `import`).    If so, then this is expected.  `mime@4`+  is ESM only.

You'll need to configure your nest / your project to compile to ESM.  Either that or pin your `mime` dependency to version 3.

**Comment by balayogesh007** [comment]
I tried to your sample project but still getting the same error.
![image](https://github.co@broofa r-attachments/assets/44678f56-7ea2-489d-84ac-26ae82b78420)
@broofa

**Comment by broofa** [comment]
First, my apologies for not realizing that this was a runtime error rather than a build-time error.  (@uszakow for future reference, MRE's work best when they include a detailed recipe for recreating the problem.   But I do appreciate that you provided a repo that allowed me to reproduce the issue.)

Speaking of which ... the issue here is simply that NestJS doesn't support ESM-only modules:
  * https://stackoverflow.com/questions/74830166/unable-to-import-esm-module-in-nestjs
  * https://github.com/nestjs/nest/pull/8736

... and `mime@4` and beyond is ESM-only.    The README is very clear about that, and it's not a decision I'm interested in revisiting.

Note, too, that despite [this comment](https://github.com/nestjs/nest/pull/8736#issuecomment-2011398600) by NestJS creator, @kamilmysliwiec, node's emerging (experimental) support for `require()`ing ESM modules doesn't seem to solve this problem.  At least not yet... (that or I'm misunderstanding how this is supposed to work)...

```
$ node --version
v22.0.0

$ node --experimental-require-module ./node_modules/.bin/nest start
(node:49033) ExperimentalWarning: Support for loading ES Module in require() is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

/private/tmp/nest-test-project/dist/app.service.js:11
const mime_1 = require("mime");
               ^
Error [ERR_REQUIRE_ESM]: require() of ES Module /private/tmp/nest-test-project/node_modules/mime/dist/src/index.js from /private/tmp/nest-test-project/dist/app.service.js not supported.
```

## Solution (for now)

Pin your `mime` dependency to `mime@3`, which is CJS, as follows:
```
npm install mime@3 @types/mime@3
```
